# Generated by Django 3.1.7 on 2021-03-10 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tw', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
